### ISSUE TITLE
ImportError: no module named 'ustruct'

### ISSUE THREAD

**Issue by siddacious** [adafruit/Adafruit_CircuitPython_MPL3115A2#1]
It appears that the updates mentioned in CP issue #205 (Refine `ustruct` into `struct` in shared-bindings and shared-module) didn't make their way here. We should patch this library to include the same changes because as of 3.0.0-alpha.1-190-g3642fcb this library generates an ImportError:

```
>>> import board
>>> import busio
>>> import adafruit_mpl3115a2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "adafruit_mpl3115a2.py", line 34, in <module>
ImportError: no module named 'ustruct'
```

**Comment by ladyada** [comment]
thanks for the fix!

**Comment by dapowers87** [comment]
It appears that this same issue is appearing in the Adafruit MicroPython TSL2561. Is it the same root cause?

**Comment by tannewt** [comment]
Yup! Are you using the latest version of the libraries? It looks like the latest TSL2561 driver doesn't use it directly: https://github.com/adafruit/Adafruit_CircuitPython_TSL2561/blob/master/adafruit_tsl2561.py

**Comment by dapowers87** [comment]
Yes I just pulled down the code and ran into this issue. Could it be that
I'm missing some other libraries? Sorry, I'm really new to raspberry pi
development.

**Comment by tannewt** [comment]
These libraries are for CircuitPython which won't work on Raspberry Pi. It doesn't look like we have one for Raspberry Pi yet.

**Comment by dapowers87** [comment]
Ah, that would explain it! Sorry for the bother, thank you!
