### ISSUE TITLE
"ValueError: No I2C device at address: 0x60"

### ISSUE THREAD

**Issue by UANEMESIS** [adafruit/Adafruit_CircuitPython_MPL3115A2#31]
Hi!

I'm getting error on Raspberry Pi4 "ValueError: No I2C device at address: 0x60" with default code from example:

```
import time
import board
import adafruit_mpl3115a2

i2c = board.I2C()  

sensor = adafruit_mpl3115a2.MPL3115A2(i2c) # failing here
```

xtq@raspberrypi:~ $ sudo i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:                         -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: 60 -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- 77         

**Any ideas about why this can happens?**

**Comment by caternuson** [comment]
Please post in the forums with photos of your setup showing how everything is connected.
https://forums.adafruit.com/

**Comment by UANEMESIS** [comment]
> Please post in the forums with photos of your setup showing how everything is connected. https://forums.adafruit.com/

Here it is:
https://forums.adafruit.com/viewtopic.php?t=213986

**Comment by UANEMESIS** [comment]
Closing this issue. 
I don't want to waste time, because of unknown error on cheap device.
