### ISSUE TITLE
adafruit_mpl3115a2.py error on Raspi/i2c

### ISSUE THREAD

**Issue by zithro** [adafruit/Adafruit_CircuitPython_MPL3115A2#6]
In file "adafruit_mpl3115a2.py" starting line 117, the 2 lines: 
```
if self._read_u8(_MPL3115A2_WHOAMI) != 0xC4
    raise RuntimeError('Failed to find MPL3115A2, check your wiring!')
```
should be commented to get readings.
But then, only temperature and pressure readings work, the altitude reading makes the script hang.
What happens ? ^^

**Comment by caternuson** [comment]
Those lines notionally verify that the sensor is connected and the type expected. Can you provide more info on the issue you are having. What program are you running and what is happening?

**Comment by ladyada** [comment]
note this chip uses clock stretching, follw https://learn.adafruit.com/circuitpython-on-raspberrypi-linux/i2c-clock-stretching to enable it

**Comment by zithro** [comment]
> What program are you running and what is happening?

I used the install docs on learn.ada.com and the test script (simpletest.py) provided with the examples/library, almost unmodified : I removed the loop to get one set of readings at a time, reordered the readings so the altitude is polled last, and added a time.sleep(1) before each individual reading.
The result is Temp+Press values get displayed, then the script hangs while reading the altitude.
But the values are "14719.25Pa" and "2.312°C", which is odd for my room ^^ A BMP280 on another machine reports "99000Pa" and "26°C"

> note this chip uses clock stretching, follow https://learn.adafruit.com/circuitpython-on-raspberrypi-linux/i2c-clock-stretching to enable it

Oh, didn't know, will try that and report back ! A few questions:
- what's the drawback(s) of reducing the i2c freq ? Slower polls ? Any incompatibilities ?
- some chips need slow freqs, but are there chips that need the opposite, high freqs ? I plan on putting several sensors on the same Raspi (for example a TSL2561 is with the MPL).

**Comment by zithro** [comment]
No joy playing with the clock ! :/

Tests results :

- default i2c clock (?khz) : odd temp and press values and hangs on altitude reading
- 10khz : like without clock modification
- 5khz : same
- 4khz : same
- 3khz : no reading at all, I directly get tracebacks
- 1khz : same as 3khz

Those are the exact values I tested. Please tell me if you think about some alternate values I should test !

I tested with and without my l.117 comment:
- when the clock is too low (<3khz) there's no influence, the tracebacks prevent any reading anyway
- when the clock seems OK (as I get temp + pressure when commenting), if I don't comment I get no reading.

Attached bug reports :
- [MPL-3khz-and-less.txt](https://github.com/adafruit/Adafruit_CircuitPython_MPL3115A2/files/3304067/MPL-3khz-and-less.txt)
- [MPL-4khz-and-more.txt](https://github.com/adafruit/Adafruit_CircuitPython_MPL3115A2/files/3304068/MPL-4khz-and-more.txt)

**Comment by zithro** [comment]
I read this in the datasheet : "The I2C interface is compliant with fast mode (400 kHz), and normal mode (100 kHz) I2C standards ". So I tried 100kHz, and the script seems to hang sooner, even after 5 minutes : 
[MPL-100khz.txt](https://github.com/adafruit/Adafruit_CircuitPython_MPL3115A2/files/3304110/MPL-100khz.txt)

**Comment by barbudor** [comment]
Hi @zithro, could you please post a photo of your setup with a clear view on the module?
What are the 4 letters on the 1st line of the chip package?
Please confirm if you ever read proper/reasonable values for temp and pressure. 
Cheers

**Comment by zithro** [comment]
Hi @barbudor,
1) The setup : [MPL_closeup-attempt](https://user-images.githubusercontent.com/5737719/59809953-50b90b00-9303-11e9-93ec-b98bff6c130b.jpg), [Wiring_Breadboard-sensors](https://user-images.githubusercontent.com/5737719/59809954-50b90b00-9303-11e9-98a2-3f1d8055c007.jpg), [Wiring_Pi-Breadboard](https://user-images.githubusercontent.com/5737719/59809955-50b90b00-9303-11e9-9fe4-80cd1fb333f9.jpg).
I only had an ersatz of a GoPro at hand, sorry for the quality ... Tell me if you need better photos !
In short: 4 wires run from the Pi to the breadboard, and both sensors (MPL + TSL2561) are plugged on the breadboard, sharing all lines. The TSL works fine, and I tried without the TSL too. Nothing else is plugged.
The sensor looks brand new, no sign of wear or dust. Before trying the sensor soldered, I was using a "poor-man's wiring" (like the TSL in the pics) and was getting the same results. So it's almost sure the connections are OK, and I didn't fry it ^^ The MPL gets its ~5.2v.

2) The 1st line on the chip is M3PR (2nd line CQOM).

3) I never had proper results.
The temperature and the pressure fluctuate slightly around the same values (examples: 2.3125, 2.375, and 14719.500, 14719.750, 14720.000), even when warming the chip.

Are you implying the chip may be defective ? Because I don't get why the simple check on line 117 does not pass !

**Comment by barbudor** [comment]
Hi @zithro,

Thanks for the details. Needed to be sure you have a real Mpl3115A2. If it was a Chinese board instead of a genuine Adafruit, it could have been another chip such as Mpl115A2 (many people who purchase chinese BME280 boards end up with BMP280 which fails similar chip ID test).
You seem to use pretty long wires. 
You said you tested the MPL on it's own without the TSL. Was it with such long cables? 
Could try again with shortest cables as possible? If possible avoid the green breadboard if you have fem-fem cables. Keep the slow clock settings as per laydyada advice. 
And last could you print the value read from the WhoAmI register? 
Cheers

**Comment by caternuson** [comment]
Wow. This thing seriously clock stretches. Scoped it on a Metro M4:
![Screenshot from 2019-06-20 09-19-41](https://user-images.githubusercontent.com/8755041/59864867-93e3a000-933c-11e9-9ab9-4b75bbe693b0.png)
That's ~**152ms** of holding between the read/write for the WHO_AM_I query.

The slow-down-the-baud-rate trick may not work for something that long?

**Comment by ladyada** [comment]
yeep. yeah nothing will delay long enough. may just not be raspi compatible at this time !

**Comment by caternuson** [comment]
Sry. Ignore my last message if you saw it (now deleted). I wasn't mathing right. :man_facepalming: 

Maybe this will make up for it - see #7 for possible fix. :)

**Comment by caternuson** [comment]
@zithro Try updating to the 1.1.4 release when it becomes available:
https://github.com/adafruit/Adafruit_CircuitPython_MPL3115A2/releases/tag/1.1.4

**Comment by zithro** [comment]
Glory to i2c.write_then_readinto ! ^^
```
Pressure: 98639.500 pascals
Temperature: 26.938 degrees Celsius
Altitude: 225.691 meters
```
I just updated the lib to get the correct results.
So this means **without** changing the i2c baud rate : I left it at default setting, ie "i2c_arm_baudrate" **unset** (Pi 3B Rev 1.20 - BCM2835 a02082).

Thanks everyone !
Now gonna try switching from the BME280 old C/python lib to the CircuitPython/blinka one (nice tool btw) ;)
(PS: the old lib still works fine though)

@barbudor, the WhoAmI register read "2". Lucky that's not the cables fault, I plan on using longer ones ^^ What's the max ? (PS: bought the chip from modmypi, I eliminated the contraband possibility ;))
@caternuson you should have left that post/graph, that's always informative ! (Metro m2 ? graph displayed on a linux box ? A few things to discover for me ^^) And thx for the fix :)

**Comment by barbudor** [comment]
@zithro good to hear it's not the chip or the hardware.
I can't tell for the longest cable. But reducing the i2c freq may help if you start facing problems due to length. 
I'm surprised that you read '2'. It should be '0xC4'.
Good luck with your project.

**Comment by caternuson** [comment]
I would have left the post/graph it have been good info. But I was soooo wrong that it probably would do more damage than good leaving it up. And with the library change, the I2C traffic will look different now anyway.

Just glad this fixed it. Thanks for letting us know. Have fun!
